# Generated by Django 3.2.3 on 2021-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=50)),
                ('Name_of_block', models.CharField(max_length=30)),
                ('Room_number', models.CharField(max_length=50)),
                ('Maintenance_needed', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Student_Id', models.CharField(max_length=20)),
                ('Block', models.CharField(max_length=30)),
                ('Room_number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'RoomAllocation',
            },
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_block', models.CharField(max_length=30)),
                ('Room_number', models.CharField(max_length=10)),
                ('Furnitures_present', models.CharField(max_length=500)),
                ('About_toilet', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'RoomDetails',
            },
        ),
    ]
