# Generated by Django 3.2.3 on 2021-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rules', models.CharField(max_length=100)),
                ('Mess_rules', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Guideline',
            },
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
